### ISSUE TITLE
conda not installing nbdev properly on WSL2 

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#430]
@yunlongYoung reported the following problem in #428:

```
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting nbdev

...

Installing collected packages: nbconvert, nbdev
  Attempting uninstall: nbconvert
    Found existing installation: nbconvert 6.0.7
    Uninstalling nbconvert-6.0.7:
      Successfully uninstalled nbconvert-6.0.7
  Attempting uninstall: nbdev
    Found existing installation: nbdev 0.2.40
    Uninstalling nbdev-0.2.40:
      Successfully uninstalled nbdev-0.2.40
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

spyder 4.1.5 requires pyqt5<5.13; python_version >= "3", which is not installed.
spyder 4.1.5 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
spyder 4.1.5 requires jedi==0.17.1, but you'll have jedi 0.18.0 which is incompatible.
spyder 4.1.5 requires parso==0.7.0, but you'll have parso 0.8.1 which is incompatible.
Successfully installed nbconvert-6.0.7 nbdev-1.1.12
(base) ➜  young git:(master) ✗ nbdev_build_lib
Converted 00_core.ipynb.
Converted index.ipynb.
(base) ➜  young git:(master) ✗ nbdev_build_docs
converting: /mnt/c/Users/drago/Documents/jupyter/young/00_core.ipynb
converting: /mnt/c/Users/drago/Documents/jupyter/young/index.ipynb
converting /mnt/c/Users/drago/Documents/jupyter/young/index.ipynb to README.md
(base) ➜  young git:(master) ✗
```

Addtional mention, when I run 'pip3 install nbdev', it not worked on ubuntu20.04 under wsl2. So I install nbdev by install anaconda first, then use 'conda install -c fastai nbdev', it succeed. and then because of default nbdev version is 0.2.40 in conda, an error "'HTMLExporter' object has no attribute 'template_path'" occured. But 'pip3 install -U nbdev' fixed that. All this makes me a little dizzy.

Strongly suggest everyone should run 'pip install -U nbdev' or 'pip3 install -U nbdev' after install nbdev by anaconda, can you kindly metion this in the tutorial or install instruction?

**Comment by hamelsmu** [comment]
I'll close this in favor of #431
