### ISSUE TITLE
NBDev[1.1.3] `nbdev_build_docs` not working with latest fastcore[1.3.1] 'list' object has no attribute 'map_filter'

### ISSUE THREAD

**Issue by ZivotJeKrasny** [fastai/nbdev#299]
Latest/current/1.1.3 version of NBDev does not work with latest/current/1.3.1 fastcore while running `nbdev_build_docs` command.
Error with message `'list' object has no attribute 'map_filter'` is shown and no `html` file is created.

It seems that `fastcore` is not compatible with NBDev after this commit  https://github.com/fastai/fastcore/commit/e72fe807d0822206e947be1fb015e7691e2a63c3 where function `L.map_filter` was removed.

In NBDev the function `L.map_filter` is used in function `add_show_docs` https://github.com/fastai/nbdev/blob/master/nbs/03_export2html.ipynb (https://github.com/fastai/nbdev/blob/master/nbdev/export2html.py#L276).

Temporary solution is to install fastcore in previous version `pip install fastcore==1.3.0`.

**Comment by hamelsmu** [comment]
This is also breaking in CI: https://github.com/fastai/nbdev/pull/300/checks?check_run_id=1339437962#step:4:70

cc: @jph00 

I'm investigating now.

**Comment by hamelsmu** [comment]
related issue https://github.com/fastai/fastcore/issues/164

Found the answer in the release notes just need to change this to 

> Redundent L.map_filter removed (since L.map.filter does the same thing)

Working on it now

**Comment by hamelsmu** [comment]
Looks like @jph00 beat me to it this is fixed by https://github.com/fastai/nbdev/commit/fd4cfac2a85875e9b6f9dad3012b34fc9e8a6a67
